name: Sync tidy-downloads.js from Sine (DISABLED)

on:
  # Disabled for fork - remove this comment and uncomment below to re-enable
  # repository_dispatch:
  #   types: [sync_tidy]

jobs:
  # sync:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Zen-Tidy-Downloads
  #       uses: actions/checkout@v4
  #
  #     - name: Download tidy-downloads.js from Sine
  #       run: |
  #         curl -o tidy-downloads.uc.js https://raw.githubusercontent.com/Anoms12/Sine/main/mods/zen-tidy-downloads/tidy-downloads.js
  #
  #     - name: Commit and push changes
  #       run: |
  #         git config user.name "github-actions"
  #         git config user.email "github-actions@github.com"
  #         git add tidy-downloads.uc.js
  #         git diff --cached --quiet || git commit -m "Auto-sync: updated tidy-downloads.js from Sine"
  #         git push
